Android support
bkaradzic/bgfx.cmake-archived pull request #10
Opened 2021-05-15 15:41 UTC by Mempler

At the moment `bgfx.cmake` does not compile for Android, those changes allow it to be compiled for Android.

2021-05-15 16:34 UTC, e-erdal approved these changes

2021-05-16 03:59 UTC, bwrsandman commented
What commands are you running to cross compile for android? I'd like to test it.

2021-05-16 14:33 UTC, Mempler commented
> What commands are you running to cross compile for android? I'd like to test it.
> Could you write up the instructions in the building section of the README?

Literally just add_subdirectory and creating an android studio project. Nothing fancy.

2021-05-16 17:19 UTC, bwrsandman commented
Do you get this error?
```
~/AndroidStudioProjects/testbgfx/app/src/main/cpp/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at ~/AndroidStudioProjects/testbgfx/app/src/main/cpp/bgfx.cmake/cmake/version.cmake:26 (file):
  file failed to open for reading (No such file or directory):

    ~/AndroidStudioProjects/testbgfx/app/src/main/cpp/bgfx.cmake/bgfx/scripts/bgfx.idl
Call Stack (most recent call first):
  bgfx.cmake/CMakeLists.txt:15 (include)

```

2021-05-16 17:40 UTC, bwrsandman commented
Do you get this error? Even with examples turned off.
```
~/AndroidStudioProjects/testbgfx/app/src/main/cpp/bgfx.cmake/bgfx/examples/common/entry/entry_android.cpp:19:10: fatal error: 'android_native_app_glue.h' file not found
```

2021-05-16 17:48 UTC, bwrsandman requested changes
Please add `target_include_directories` to all targets using `android_native_app_glue.h`

2021-05-16 17:53 UTC, bwrsandman commented
You might also want to fix or disable tools building in Android:
```
Build command failed.
Error while executing process ~/android/cmake/3.10.2.4988404/bin/ninja with arguments {-C ~/AndroidStudioProjects/testbgfx/app/.cxx/cmake/debug/armeabi-v7a geometryc geometryv native-lib shaderc texturec texturev}
ninja: Entering directory `~/AndroidStudioProjects/testbgfx/app/.cxx/cmake/debug/armeabi-v7a'
[1/3] Linking CXX executable bgfx.cmake/texturev
FAILED: bgfx.cmake/texturev 
: && ~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16 --gcc-toolchain=~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections bgfx.cmake/CMakeFiles/texturev.dir/bgfx/tools/texturev/texturev.cpp.o  -o bgfx.cmake/texturev  bgfx.cmake/libexample-common.a bgfx.cmake/libbgfx.a -lEGL bgfx.cmake/libbimg.a bgfx.cmake/libastc-codec.a bgfx.cmake/libastc.a bgfx.cmake/libedtaa3.a bgfx.cmake/libetc1.a bgfx.cmake/libetc2.a bgfx.cmake/libiqa.a bgfx.cmake/libsquish.a bgfx.cmake/libnvtt.a bgfx.cmake/libpvrtc.a bgfx.cmake/libdear-imgui.a bgfx.cmake/libbx.a -landroid -llog bgfx.cmake/libmeshoptimizer.a -lX11 -latomic -lm && :
~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lX11
~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[2/3] Linking CXX executable bgfx.cmake/geometryv
FAILED: bgfx.cmake/geometryv 
: && ~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16 --gcc-toolchain=~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections bgfx.cmake/CMakeFiles/geometryv.dir/bgfx/tools/geometryv/geometryv.cpp.o  -o bgfx.cmake/geometryv  bgfx.cmake/libexample-common.a bgfx.cmake/libbgfx.a -lEGL bgfx.cmake/libbimg.a bgfx.cmake/libastc-codec.a bgfx.cmake/libastc.a bgfx.cmake/libedtaa3.a bgfx.cmake/libetc1.a bgfx.cmake/libetc2.a bgfx.cmake/libiqa.a bgfx.cmake/libsquish.a bgfx.cmake/libnvtt.a bgfx.cmake/libpvrtc.a bgfx.cmake/libdear-imgui.a bgfx.cmake/libbx.a -landroid -llog bgfx.cmake/libmeshoptimizer.a -lX11 -latomic -lm && :
~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lX11
~/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[3/3] Linking CXX executable bgfx.cmake/shaderc
ninja: build stopped: subcommand failed.
```

2021-05-16 17:57 UTC, bwrsandman commented
There's also the question of building shaders when cross compiling. In the past when I tried this, I had a special case when cross compiling to use a host-system compiled version of shaderc.

2021-07-05 08:55 UTC, thomasreiser commented
Hi @bwrsandman 

in my case (by adding bgfx.cmake via `add_subdirectory`) the build fails because of missing `android_native_app_glue.h`:

```
option(BGFX_BUILD_EXAMPLES "" OFF)
if(ANDROID)
    option(BGFX_BUILD_TOOLS "" OFF)
endif()
option(BGFX_INSTALL "" OFF)
add_subdirectory(3rdparty/bgfx.cmake)
```

Error output:
```
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ../../../../../../3rdparty/bgfx.cmake/bgfx/examples/common/entry/entry_android.cpp:19:10: fatal error: 'android_native_app_glue.h' file not found
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   #include <android_native_app_glue.h>
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   1 error generated.
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   [5/8] Linking CXX executable ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/shaderc
2021-07-05T10:42:57.676+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ninja: build stopped: subcommand failed.
```

2021-08-09 15:25 UTC, e-erdal commented
Closing due to inactivity, might take a look on that later on.

2021-08-09 15:26 UTC, closed without merging