Improvments on the shader compiler utility
bkaradzic/bgfx.cmake-archived pull request #193
Opened 2023-03-24 15:35 UTC by object71

The custom command didn't recognize bgfx::shaderc and the generator expression seems bettter. I also added an include option since it might be important to be able to define those.

2023-03-27 09:23 UTC, object71 commented on cmake/bgfxToolUtils.cmake
> +		if(ARGS_TYPE STREQUAL "VERTEX" OR ARGS_TYPE STREQUAL "FRAGMENT")
Moving this here since in BGFX the direct x shaders for an embedded shader are by default enabled in linux builds. So if you're using this utility function with an embedded_shader.h then you would want to have dx9 shaders generated.

2023-04-02 10:05 UTC, object71 commented
Hey @bwrsandman These are some small improvements on the shader compilation helper. Mainly it wasn't working for me because it couldn't resolve `bgfx::shaderc` so I replaced it with `$<TARGET_FILE:shaderc>`. I also got a few more ideas though - since the internal implementation adds custom commands that are not linked to any targets it would be benefitial to set the output files into a variable so that some target can depend on those files. Otherwise some platforms don't execute the custom command to generate the shaders. And I found that I was missing the feature for setting an include directory.

Are these changes okay?

2023-04-02 11:00 UTC, bwrsandman commented
I'm curious to know more about your setup. If we can fix your target and avoid using `target_file`, I would prefer it.

2023-04-02 14:43 UTC, object71 commented
You can check out https://github.com/Paper-Cranes-Ltd/big2-stack but I just got an error that it doesn't recognize bgfx::shaderc

2023-04-02 19:17 UTC, bwrsandman commented
Looks like you're using fetchcontent. I'll have to test this.
My first guess is maybe the namespace doesn't exist.
The target should be put in the right namespaces if the library is installed and you use the generated targets there.

2023-04-03 06:14 UTC, object71 commented
Is the $<TARGET_FILE> generator going to break installed targets?

2023-04-23 05:59 UTC, object71 commented
@bwrsandman did you manage to test it out?

2023-04-23 11:42 UTC, bwrsandman commented
Sorry, I completely forgot.

I've done some testing now and here's a better solution that works with fetchcontent and installed targets.
In bgfxToolUtils.cmake, for each executable (bin2c, texturec, geometryc and shaderc) add this

```cmake
if (NOT TARGET shaderc AND TARGET bgfx::shaderc)
    add_executable(bgfx::shaderc ALIAS shaderc)
endif()
```

I'm not sure if it's better to put in the function namespace or in the top scope.

2023-04-29 19:39 UTC, mode777 commented
I have the same problem where bgfx::shaderc was not found when including bgfx.cmake as a subdirectory in cmake. I added this to my top-level CMakeLists.txt so now, at least it will run the command
```cmake
if (NOT TARGET bgfx::shaderc AND TARGET shaderc)
    add_executable(bgfx::shaderc ALIAS shaderc)
endif()
```

2023-05-01 03:31 UTC, bwrsandman requested changes
In bgfxToolUtils.cmake, for each executable (bin2c, texturec, geometryc and shaderc) add this

```cmake
if (NOT TARGET shaderc AND TARGET bgfx::shaderc)
    add_executable(bgfx::shaderc ALIAS shaderc)
endif()
```

2023-05-01 09:05 UTC, Carbone13 commented
On Ninja + MSVC, it doesn't work, $<TARGET_FILE> solution works, but the one proposed by @bwrsandman don't
My CMakeLists look like :
`project(repro)
add_subdirectory(bgfx.cmake)

bgfx_compile_shader_to_header(
  TYPE VERTEX
  SHADERS vs.sc
  VARYING_DEF varying.def.sc
  OUTPUT_DIR ${CMAKE_BINARY_DIR}/include/generated/shaders
)

add_executable(repro main.cpp vs.sc)`

2023-05-01 09:45 UTC, object71 commented
It doesn't work for me either even though I added it. Target file is the only solution that works correctly since it also implicitly handles the depenedency correctly.

2023-05-01 13:08 UTC, bwrsandman commented
The problem with `$<TARGET_FILE:shaderc>` is that is breaks installed targets:
```
[cmake] CMake Error at cmake-build-presets/ninja-multi-vcpkg/vcpkg_installed/x64-linux/share/bgfx/bgfxToolUtils.cmake:606 (add_custom_command):
[cmake]   Error evaluating generator expression:
[cmake] 
[cmake]     $<TARGET_FILE:shaderc>
[cmake] 
[cmake]   No target "shaderc"
[cmake] Call Stack (most recent call first):
[cmake]   src/CMakeLists.txt:46 (bgfx_compile_shader_to_header)
```

2023-05-01 13:15 UTC, bwrsandman commented
@Carbone13 @object71 Are you both using msvc and ninja?

Can you share the error message? When I tried the code it worked so it might just need some tuning.

2023-05-01 13:45 UTC, bwrsandman requested changes
The issue I'm seeing with the code as written is that the condition is not satisfied in the scope of `bgfxToolUtils.cmake`, not to mention that `NOT TARGET shaderc` shouldn't have `NOT`.

I've got a solution that seems to work. Can you try replacing `_bgfx_define_alias_if_missing` with the following changes? It would also need the same for bin2c, texturec, geometryc. Either of the `if` statements might not be needed.

The changes in examples.cmake would allow CI coverage of your usecase. Nice to have would be replacing `add_bgfx_shader` with a `bgfx_compile_shader_to_binary` in `bgfxToolUtils.cmake` and simplifying `bgfx_compile_shader_to_header` to be common code that adds `BIN2C` as an argument.

```patch
diff --git a/cmake/bgfx/examples.cmake b/cmake/bgfx/examples.cmake
index 81e1d47..389a051 100755
--- a/cmake/bgfx/examples.cmake
+++ b/cmake/bgfx/examples.cmake
@@ -105,7 +105,7 @@ function(add_bgfx_shader FILE FOLDER)
 
                foreach(OUT ${OUTPUTS})
                        list(APPEND OUTPUT_FILES ${${OUT}_OUTPUT})
-                       list(APPEND COMMANDS COMMAND "$<TARGET_FILE:shaderc>" ${${OUT}})
+                       list(APPEND COMMANDS COMMAND "bgfx::shaderc" ${${OUT}})
                        get_filename_component(OUT_DIR ${${OUT}_OUTPUT} DIRECTORY)
                        file(MAKE_DIRECTORY ${OUT_DIR})
                endforeach()
diff --git a/cmake/bgfx/shaderc.cmake b/cmake/bgfx/shaderc.cmake
index bed59a0..5e61729 100644
--- a/cmake/bgfx/shaderc.cmake
+++ b/cmake/bgfx/shaderc.cmake
@@ -54,6 +54,12 @@ if(BGFX_BUILD_TOOLS_SHADER AND BGFX_CUSTOM_TARGETS)
        add_dependencies(tools shaderc)
 endif()
 
+if(BGFX_BUILD_TOOLS_SHADER)
+       if (TARGET shaderc AND NOT TARGET bgfx::shaderc)
+               add_executable(bgfx::shaderc ALIAS shaderc)
+       endif()
+endif()
+
 if(ANDROID)
        target_link_libraries(shaderc PRIVATE log)
 elseif(IOS)
```

2023-05-01 16:22 UTC, object71 commented
With your last suggestions it works now for me. I squashed the commits to a single one.

2023-05-01 17:37 UTC, bwrsandman requested changes

2023-05-01 17:37 UTC, bwrsandman commented on cmake/bgfx/geometryc.cmake
> +	if(TARGET geometryc AND NOT TARGET bgfx::geometryc)
Have you checked if this line is necessary? Seems like we can assume that the executable code exists since it's declared above, also the namespaces target shouldn't exist since it's only ever created here and in the config of an install which wouldn't include this file.

2023-05-01 19:17 UTC, bwrsandman approved these changes
Looks good!

2023-05-02 04:55 UTC, merged