Fix clang on WIN32 without MINGW
bkaradzic/bgfx.cmake-archived pull request #6
Opened 2021-05-06 10:14 UTC by Mempler

clang does not seem to be supported on the windows platform, this PR just adds support for it, so you wont require MINGW/MSYS2 to compile bgfx.cmake

2021-05-06 15:59 UTC, e-erdal approved these changes

2021-05-07 13:18 UTC, bwrsandman requested changes

2021-05-07 13:18 UTC, bwrsandman commented on cmake/bx.cmake
> +elseif ( NOT MSVC AND CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND NOT MINGW ) # clang still uses msvc headers on windows.
It seems like this will include `compat/msvc` on non windows platforms.
Also, `NOT MSVC` is redundant here.
Since the two sides of the if statement are identical maybe change it to:

```cmake
if ( MSVC OR (WIN32 AND NOT MINGW AND CMAKE_CXX_COMPILER_ID MATCHES "Clang") )
```

2021-05-07 13:29 UTC, bwrsandman commented on cmake/bx.cmake
> +elseif ( NOT MSVC AND CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND NOT MINGW ) # clang still uses msvc headers on windows.
You might want to generalize it more to:
```cmake
if ( WIN32 AND NOT MINGW ) # includes MSVC, CLANG, INTEL, etc for c++ and c compilers.
```

It can be simplified even further by putting the MINGW conditional first
```
if ( MINGW )
  # ...
elseif ( CYGWIN ) # potential for the future addition, don't add this.
  # ...
elseif ( WIN32 )  # includes MSVC, CLANG, INTEL, etc for c++ and c compilers on windows.
  # ...
```

2021-05-07 20:21 UTC, bwrsandman approved these changes

2021-05-07 20:52 UTC, merged